//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Das_Des_2.Models.Peli
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vote
    {
        public int idVoto { get; set; }
        public int valueVoto { get; set; }
        public int idMovie { get; set; }
    
        public virtual Movie Movie { get; set; }
    }
}
